# Use Node.js LTS version
FROM node:20-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install


# Copy app source
COPY . .

# Expose port
EXPOSE 5000

# Start the app
CMD ["npm", "run", "dev"] 