version: '3.8'
services:
  app:
    build:
      context: ../backend                # directory to build from
      dockerfile: Dockerfile.prod        # specific docker file
    volumes:
      - ../backend:/usr/src/app
    env_file:
      - .env.production.local
    ports:
      - "5000:5000"
    command: npm run prod
